config/routes.rb
Rails.application.routes.draw do
  post "accept_booking/:id", to: "pages#accept_booking", as: :accept_booking
  post "decline_booking/:id", to: "pages#decline_booking", as: :decline_booking
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard", as: :dashboard

  resources :requests, only: [:show, :edit, :update]
  resources :requests, only: [:create]  #request create must happen after payment create

  resources :miles_profiles, except: [:show]
  resources :bookings, only: [:new, :create] do
    resources :passengers, only: [:create]
    resources :payments, only: :new
  end

  get 'bookings/:id', to: "bookings#show", as: :booking
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :miles_profile, optional: true
  has_many :payments
  has_many :passengers
  has_one :request

  validates :departure_date, :return_date, presence: true
  validates :departure, presence: true
  validates :arrival, presence: true
  # before_save :set_miles_profile


  private

  # def set_miles_profile
  # end

  def end_date_after_start_date
    return if departure_date.blank? || return_date.blank?

    if return_date < departure_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new]

  # def index
  #   @bookings = Booking.all
  # end

  def show
    @booking = Booking.find(params[:id])
    # @past_bookings = Booking.where("end_date < ?", Date.today)
  end

  def create
    departure_date = params[:departure_date]
    return_date = params[:return_date]
    @booking = Booking.new(bookings_params)
    @booking.departure_date = departure_date
    @booking.return_date = return_date
    @booking.user = current_user
    #insert that into the cards
    #get the price per mile * amount of miles for booking.price
    # need to change later
    miles_profile = MilesProfile.where('amount > ?', @booking.amount_of_miles).sample
    unless miles_profile.nil?
      @booking.status = 'pending'
      @booking.price = (@booking.amount_of_miles * miles_profile.price) / 1000 #calculate price based on user selection
      @booking.miles_profile = miles_profile
      if @booking.save!
        passenger = Passenger.new(passenger_params)
        passenger.booking_id = @booking.id
        @requests = Request.new
        @requests.confirmed = 'pending'
        @requests.booking = @booking
        @requests.save!
        if passenger.save!
          # redirect_to dashboard_path
          session = Stripe::Checkout::Session.create(
              payment_method_types: ['card'],
              line_items: [{
                name: "#{@booking.departure} to #{@booking.arrival}",
                amount: @booking.price * 100,
                currency: 'usd',
                quantity: 1
              }],
              success_url: dashboard_url,
              cancel_url: dashboard_url
            )
          flash[:notice] = 'Your flight booking has been requested!'
          @booking.update(checkout_session_id: session.id)
          redirect_to new_booking_payment_path(@booking)
        else
          render "bookings/new"
        end
      else
        render "bookings/new"
      end
    else
      flash[:alert] = "Sorry, no seller available"

      redirect_to miles_profiles_path(departure: params[:booking][:departure], arrival: params[:booking][:arrival])
    end
  end

  def new
    @airline = params[:airline]
    @class = params[:amount_of_miles].split("-").first
    @departure = params[:departure]
    @arrival = params[:arrival]
    @places = session[:params]
    @booking = Booking.new
    if user_signed_in?
      if current_user.present?
      else
        redirect_to new_user_registration_path
        flash[:alert] = 'Please sign up to book this flight.'
      end
    else
      redirect_to user_session_path
      flash[:alert] = 'Please log in to book this flight.'
    end
    # need to create new passenger here
  end

  private

  def bookings_params
    params.require(:booking).permit(:flight_number, :departure, :arrival, :seat_class, :departure_date, :return_date, :price, :amount_of_miles)
  end

  def passenger_params
    params.require(:passenger).permit(:first_name, :last_name, :birth_date)
  end
end

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<div style="background-color: white">
  <div class="listing-container pb-3" style="color: black">
    <div class="col-md-8 offset-md-2">
      <div class="listing-row">
        <h2 id="listing-title" style="">Flight Information</h2>
        <div class="row-listing-form">
          <div class="card auto-margined w-100" style="border-style: none;">
          <div class="card">
            <div class="card-header blue-header">
              <h5 class="booking-card-subtitle" style="margin-bottom: auto;"><%= @departure %> <!-- <span style="color:black"> -->to</span> <%= @arrival %></h5>
              <h5 class="booking-card-subtitle" style="margin-top: auto;"></h5>
            </div>
            <div class="booking-card-body">
            <div class="d-flex justify-content-between mb-2">

              <div class="location-info">
                <h3 id="departure-iata" class="mb-0"><%= "#{@departure[0..2].upcase}"%></h3>
                <p><%= "#{@departure[3..-1].upcase}"%> </p>
              </div>

              <div class=""><div style="width: 60px"><%= image_tag "https://static.thenounproject.com/png/2969485-200.png" %></div></div>

              <div class="location-info">
                <h3 id="arrival-iata" class="mb-0"><%=  "#{@arrival[0..2].upcase}"%></h3>
                <p><%= "#{@arrival[3..-1].upcase}"%></p>
              </div>


            </div>

            <div class="d-flex justify-content-between">
            <div class=""></div>
            <div class=""><p><%= %></p></div>
            </div>


<!--
            <div>
            <div style="width:100%">
              <p style="margin:0 auto; text-align: center">Flight number</p>
            </div>
            <div class="d-flex justify-content-between" style="width: 100%">
            <div class="p-5 d-flex"><input type="checkbox"><p>arrival</p></div>
            <div class="p-5">departure</div>
            </div>
            </div>
 -->
            <div class="d-flex justify-content-between">
              <div class=""><span id="departure-date-value"></span></div>
              <div class=""><span id="arrival-date-value"></span></div>
            </div>
            <div id="flight-numbers" data-ek="<%= asset_path 'airline_logos/EK.png' %>">

            </div>
            </div>
          </div>
        </div>
        <%= simple_form_for(@booking) do |f|%>
          <div class="d-flex justify-content-center">
            <div class="form-group w-50 mr-5">
              <label for="departure" style="color: black;">Departure Date</label>
              <input type="text" readonly="readonly" name="departure_date" class="form-control booking-form" id="depart-date">
            </div>
            <div class="form-group w-50">
              <label for="arrival" style="color: black;">Return Date</label>
              <input type="text" readonly="readonly" name="return_date" class="form-control booking-form" id="return-date">
            </div>
          </div>

          <%= f.input :flight_number, input_html: { placeholder:"Enter your flight number here", readonly: false, class: 'booking-form' } %>
          <%= f.input :amount_of_miles, as: :hidden, input_html: { value: params[:amount_of_miles].split("-").last } %>
          <%= f.input :seat_class, label: "Seating class", input_html: { value: @class , readonly: true, class: 'booking-form' } %>
          <%= f.input :departure, input_html: {value: @departure, readonly: true, class: 'booking-form' } %>
          <%= f.input :arrival, input_html: {value: @arrival, readonly: true, class: 'booking-form' } %>
          <h2 id="listing-title" style="color: $blue">Passenger Information</h2>
          <%= simple_fields_for :passenger do |o| %>
           <div class="form-group w-100">
            <label for="passenger_first_name">First / Given name (as in passport)</label>
            <%= o.input :first_name, label: false, input_html: { class: 'booking-form'} %>
            <label for="passenger_last_name">Last name/ Family name (as in passport)</label>
            <%= o.input :last_name, label: false, input_html: { class: 'booking-form'} %>
            <%= o.input :birth_date, as: :date, html5: true, input_html: {id: 'birth-date', class: 'booking-form'} %>
          <% end %>

          <!-- <input type="text" name="passenger_name">
          <input type="text" name="passenger_name2">
          <input type="text" name="passenger_name3"> -->
<!--           <div class="row">
  <div class="col-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-Passenger 1-tab" data-toggle="pill" href="#v-pills-Passenger 1" role="tab" aria-controls="v-pills-Passenger 1" aria-selected="true">Passenger 1</a>
      <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-Passenger 2" aria-selected="false">Passenger 2</a>
      <a class="nav-link" id="v-pills-Passenger 3-tab" data-toggle="pill" href="#v-pills-Passenger 3" role="tab" aria-controls="v-pills-Passenger 3" aria-selected="false">Passenger 3</a>
      <a class="nav-link" id="v-pills-Passenger 4-tab" data-toggle="pill" href="#v-pills-Passenger 4" role="tab" aria-controls="v-pills-Passenger 4" aria-selected="false">Passenger 4</a>
    </div>
  </div>
  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-Passenger 1" role="tabpanel" aria-labelledby="v-pills-Passenger 1-tab">...</div>
      <div class="tab-pane fade" id="v-pills-Passenger 2" role="tabpanel" aria-labelledby="v-pills-Passenger 2-tab">...</div>
      <div class="tab-pane fade" id="v-pills-Passenger 3" role="tabpanel" aria-labelledby="v-pills-Passenger 3-tab">...</div>
      <div class="tab-pane fade" id="v-pills-Passenger 4" role="tabpanel" aria-labelledby="v-pills-Passenger 4-tab">...</div>
    </div>
  </div>
</div> -->



          <div class="d-flex justify-content-between">
          <%= link_to "Back to Flight Search", miles_profiles_path(departure: @places[0], arrival: @places[1]), class: "purple-btn slim slima" %>
          <%= f.button :submit, "Confirmation and Payment", class: "purple-btn slim" %>
          <%#= link_to "Make a Booking Request", payment_path(payment), class: "btn btn-outline-primary"  %>
          </div>
       </div>
    <% end %>
      </div>
    </div>
  </div>
</div>

<div id="airline-name" data-airline="<%= @airline %>" data-airline="<%= @airline %>"></div>



<script>
  const departInput = document.querySelector("#depart-date")
  const departDate = document.querySelector("#departure-date-value")
  departInput.addEventListener("change", (e) => {
    var utc= (new Date(e.target.value)).toUTCString()
    departDate.innerText = utc.split(" ").slice(0,4).join(" ")
  })
  const arrivalInput = document.querySelector("#return-date")
  const arrivalDate = document.querySelector("#arrival-date-value")
  arrivalInput.addEventListener("change", (e) => {
    var utc= (new Date(e.target.value)).toUTCString()
    arrivalDate.innerText = utc.split(" ").slice(0,4).join(" ")
  })
</script>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row row-grid justify-content-center">
    <div class="col-lg-9 order-lg-2">
<!--                     this is where the content of request card start                           -->
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-5 col-lg-8">
              <span class="h6">Booking Details</span>
            </div>
            <div class="col-7 col-lg-4 text-right">
              <i class="fas fa-user-friends mr-2" width="40"></i>
            </div>
          </div>
        </div>
          <ul class="list-group list-group-flush" style="padding: 0 0 1px 1px;">
            <li class="list-group-item">
              <div class="row align-items-center">
                <div class="col-sm-4"><small class="h6 text-sm mb-3 mb-sm-0">Status</small></div>
                <div class="col-sm-5">
                  <strong><%= @booking.status.capitalize %></strong>
                </div>
                <div class="col-sm-3 text-sm-right">
                  <% if @booking.request.photo.blank? %>
                  <%= simple_form_for(@booking.request) do |f| %>
                    <%= f.input :photo, input_html: { class: 'hidden d-none', id: "photo_input" }, label_html: { class: 'btn-blue btn-sm btn-info rounded-pill py-2 px-4 mt-3 mt-sm-0'}, label: ' Upload ticket'%>
                    <%= f.input :photo_cache, as: :hidden %>
                    <%= f.button :submit, "Submit", class: 'btn-blue btn-sm btn-info rounded-pill py-2 px-4 my-3 mt-sm-0' %>
                  <% end %>
                <% else %>
                  <%= link_to cl_image_path @booking.request.photo, download: 'hehe.png' do %>
                    <p class="btn-blue btn-info rounded-pill mt-3 mt-sm-0">See attachment</p>
                  <% end %>
                <% end %>
                </div>
              </div>
            </li>
            <li class="list-group-item">
              <div class="row">
                <div class="col-sm-4"><small class="h6 text-sm mb-3 mb-sm-0">Trip Details</small></div>
                <div class="col-sm-8">
                  <!-- First card -->
                  <div class="row mb-3">
                    <div class="col-6">
                      <p>From: <%= @booking.departure %></p>
                      <p><%= @booking.flight_number %></p>
                    </div>
                    <div class="col-6 actions text-right">
                      <p>Departure Date: <br><%= @booking.departure_date.strftime("%d %B %Y") %></p>
                    </div>
                  </div>
                  <!-- Second card -->
                  <div class="row">
                    <div class="col-6">
                      <p>To: <%= @booking.arrival %></p>
                      <p><%= @booking.flight_number %></p>
                    </div>
                    <div class="col-6 actions text-right">
                      <p>Return Date: <br><%= @booking.return_date.strftime("%d %B %Y") %></p>
                      <br>
                    </div>
                  </div>
                </div>
              </div>
            </li>
            <li class="list-group-item">
              <div class="row">
                <div class="col-sm-4"><small class="h6 text-sm mb-3 mb-sm-0">Passenger Details</small></div>
                <div class="col-sm-8">
                  <p class="mb-0">
                    <div class="uk-inline">
                      <button class="uk-button uk-button-default" type="button">Passenger 1</button>
                      <div uk-dropdown="mode: click">First Name: <%= @booking.passengers.first.first_name %>
                    Last Name: <%= @booking.passengers.first.last_name %>
                    Date of Birth: <%= @booking.passengers.first.birth_date.strftime("%d %B %Y") %></div>
                   </div>
                  </p>
                </div>
              </div>
            </li>
            <li class="list-group-item">
              <div class="row">
                <div class="col-sm-4"><small class="h6 text-sm mb-3 mb-sm-0">Earnings</small></div>
                <div class="col-sm-8">
                  <strong>$<%= @booking.price %><small> U.S Dollar</small></strong>
                </div>
              </div>
            </li>
            <li class="list-group-item">
              <div class="row">
                <div class="col-sm-4"><small class="h6 text-sm mb-3 mb-sm-0">Require</small></div>
                <div class="col-sm-8">
                  <p class="mb-0">
                    <strong><%= @booking.amount_of_miles %></strong> <%= @booking.miles_profile.programme %> Miles
                  </p>
                </div>
              </div>
            </li>
          </ul>
        </div>
        <div class="order-lg-3 mt-5 mb-5">
          <%= link_to "Back to dashboard", dashboard_path(request), class: 'purple-btn'  %>
        </div>
      </div>
<!--                     this is where the content of request card ends                          -->
    </div>
  </div>
<!-- <script>
  const input = document.querySelector("#photo_input");
  const form = document.querySelector(".edit_request");
  input.addEventListener('change', (event) => {
    console.log(form)
    Rails.fire(form, 'submit');
  })
</script> -->

</div>