config/routes.rb
Rails.application.routes.draw do
  post "accept_booking/:id", to: "pages#accept_booking", as: :accept_booking
  post "decline_booking/:id", to: "pages#decline_booking", as: :decline_booking
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard", as: :dashboard

  resources :requests, only: [:show, :edit, :update]
  resources :requests, only: [:create]  #request create must happen after payment create

  resources :miles_profiles, except: [:show]
  resources :bookings, only: [:new, :create] do
    resources :passengers, only: [:create]
    resources :payments, only: :new
  end

  get 'bookings/:id', to: "bookings#show", as: :booking
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="footer footer-dark bg-gradient-primary footer-rotate mt-0">
  <div class="container">
      <div class="d-flex align-items-center justify-content-between ">
        <div class="footer-contact ">
          <h1 class="mr-3" id="milesx-logo">Miles<span style="color: #ffd500;" id="footer-x">X</span></h1>
          <address class="footer-contact__address mr-2">
            <a href="https://www.google.com/maps/place/FRii+Bali+Echo+Beach/@-8.653986,115.1282128,17z/data=!3m1!4b1!4m8!3m7!1s0x2dd238783a9f1a37:0x3224cdc2e92612b6!5m2!4m1!1i2!8m2!3d-8.6539913!4d115.1304015" title="Munduk Catu 32, 80361 Canggu, Bali, Indonesia" target="_blank" rel="external noopener" id="footer-address">Munduk Catu 32, 80361 Canggu, Bali, Indonesia</a>
          </address>
          <address class="footer-contact__address mr-2">
            <a href="mailto:nabilasiregar@tutanota.com" title="join@milesx.com" id="footer-address">join@milesx.com</a>
          </address>
          <address class="footer-contact__address mr-2">
            <a href="tel:+62 4551 7551" title="+62 4551 7551" id="footer-address">+62 4551 7551</a>
          </address>
        </div>
        <div class="footer-social ">
          <address class="footer-social__item justify-content-center justify-content-md-end mt-3 mt-md-0">
            <a href="https://www.tripadvisor.com/Attraction_Review-g190475-d5505910-Reviews-Chasing_Lights-Tromso_Troms_Northern_Norway.html" target="_blank" rel="external noopener">
              <img src="https://chasinglights.com/wp-content/uploads/2018/10/tripadvisor.svg" alt="">
            </a>
          </address>
          <address class="footer-social__item justify-content-center justify-content-md-end mt-3 mt-md-0">
            <a href="https://www.facebook.com/Nabila-Order-Coffee-Bot-110281430354358/" target="_blank" rel="external noopener">
              <img src="https://chasinglights.com/wp-content/uploads/2018/10/facebook.svg" alt="">
            </a>
          </address>
          <address class="footer-social__item justify-content-center justify-content-md-end mt-3 mt-md-0">
            <a href="https://www.instagram.com/ChasingLights/" target="_blank" rel="external noopener">
              <img src="https://chasinglights.com/wp-content/uploads/2018/10/instagram.svg" alt="">
            </a>
          </address>
          <address class="footer-social__item justify-content-center justify-content-md-end mt-3 mt-md-0">
            <a href="https://www.youtube.com/channel/UCTEEgsflzRdWN-b-CU6WGXQ" target="_blank" rel="external noopener">
              <img src="https://chasinglights.com/wp-content/uploads/2018/10/youtube.svg" alt="">
            </a>
          </address>
        </div>
      </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="fixed-top">
<nav class="uk-navbar-container uk-navbar-transparent" uk-navbar>
    <div class="uk-navbar-left">
      <a class="uk-navbar-item uk-logo"><%= link_to "Miles", root_path, class: 'our-logo' %> <span style="color:#ffd500; font-size: 27px;">X</span></a>
    </div>
    <% if user_signed_in? %>
    <div class="uk-navbar-right">
      <ul class="uk-navbar-nav">
            <li><%= link_to "Sell Miles", new_miles_profile_path, class:"nav-css" %></li>
            <!-- <li><a class="nav-css">Explore</a></li> -->
            <li>
                <a class="uk-navbar-toggle" uk-navbar-toggle-icon href="#"></a>
                <div class="uk-navbar-dropdown">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                        <li><%= link_to "Dashboard", dashboard_path %></li>
                        <li class="uk-nav-divider"></li>
                        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <% else %>
      <div class="uk-navbar-right">
        <ul class="uk-navbar-nav">
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-transparent" data-toggle="modal" data-target="#modalLogIn">Log In</button>

          <!-- Modal -->
          <div class="modal fade" id="modalLogIn" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalLogInLabel">Welcome to MilesX</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="errors"></div>
                  <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), remote: true) do |f| %>
                    <div class="form-inputs">
                      <%= f.input :email,
                                  required: false,
                                  autofocus: true,
                                  input_html: { autocomplete: "email" } %>
                      <%= f.input :password,
                                  required: false,
                                  input_html: { autocomplete: "current-password" } %>
                      <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
                    </div>
                  </div>
                <div class="modal-footer">
                  <%= f.button :submit, "Log in", class:  "btn btn-primary "%>
                  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'link-forgot-password' %>
                </div>
                  <% end %>
              </div>
            </div>
          </div>
           <!-- Button trigger modal -->
          <button type="button" class="btn btn-transparent" data-toggle="modal" data-target="#modalSignUp">Sign Up</button>

          <!-- Modal -->
          <div class="modal fade" id="modalSignUp" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Welcome to MilesX</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= simple_form_for(:user, url: user_registration_path, method: :post) do |f| %>
                    <%= f.error_notification %>

                    <div class="form-inputs">
                      <%= f.input :email,
                                  required: true,
                                  autofocus: true,
                                  input_html: { autocomplete: "email" }%>
                      <%= f.input :first_name,
                                  required: true,
                                  input_html: { autocomplete: "first_name" }%>
                      <%= f.input :last_name,
                                  required: true,
                                  input_html: { autocomplete: "last_name" }%>
                      <%= f.input :birth_date, label: "Date of Birth", as: :date, start_year: Time.now.year - 90, end_year: Time.now.year - 8, order: [:day, :month, :year],
                                  required: true
                                                                           %>
                      <%= f.input :password,
                                  required: true,
                                  hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                                  input_html: { autocomplete: "new-password" } %>
                      <%= f.input :password_confirmation,
                                  required: true,
                                  input_html: { autocomplete: "new-password" } %>
                    </div>
                </div>
                <div class="modal-footer">
                  <div class="form-actions">
                    <%= f.button :submit, "Sign up", class: 'btn btn-primary' %>
                  </div>
                </div>
                  <% end %>
              </div>
            </div>
          </div>
        </ul>
      </div>
    <% end %>
</nav>
</div>

app/views/shared/_navbar2.html.erb
<nav class="uk-navbar-container2" uk-navbar>
    <div class="uk-navbar-left">
      <a class="uk-navbar-item uk-logo"><%= link_to "Miles", root_path, class: 'our-logo-purple' %> <span style="color: #ffd500; font-size: 27px;">X</span></a>    </div>
    <% if user_signed_in? %>
    <div class="uk-navbar-right">
      <ul class="uk-navbar-nav">
            <li><%= link_to "Sell Miles", new_miles_profile_path, class:"nav2-css" %></li>
           <!--  <li><a class="nav2-css">Explore</a></li> -->
            <li>
                <a class="uk-navbar-toggle" uk-navbar-toggle-icon href="#"></a>
                <div class="uk-navbar-dropdown">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                        <li><%= link_to "Dashboard", dashboard_path %></li>
                        <li class="uk-nav-divider"></li>
                        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <% else %>
      <div class="uk-navbar-right">
        <ul class="uk-navbar-nav">
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-transparent" data-toggle="modal" data-target="#modalLogIn">Log In</button>

          <!-- Modal -->
          <div class="modal fade" id="modalLogIn" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalLogInLabel">Welcome to MilesX</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="errors"></div>
                  <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), remote: true) do |f| %>
                    <div class="form-inputs">
                      <%= f.input :email,
                                  required: false,
                                  autofocus: true,
                                  input_html: { autocomplete: "email" } %>
                      <%= f.input :password,
                                  required: false,
                                  input_html: { autocomplete: "current-password" } %>
                      <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
                    </div>
                  </div>
                <div class="modal-footer">
                  <%= f.button :submit, "Log in", class:  "btn btn-primary "%>
                  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'link-forgot-password' %>
                </div>
                  <% end %>
              </div>
            </div>
          </div>
           <!-- Button trigger modal -->
          <button type="button" class="btn btn-transparent" data-toggle="modal" data-target="#modalSignUp">Sign Up</button>

          <!-- Modal -->
          <div class="modal fade" id="modalSignUp" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Welcome to MilesX</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= simple_form_for(:user, url: user_registration_path, method: :post) do |f| %>
                    <%= f.error_notification %>

                    <div class="form-inputs">
                      <%= f.input :email,
                                  required: true,
                                  autofocus: true,
                                  input_html: { autocomplete: "email" }%>
                      <%= f.input :first_name,
                                  required: true,
                                  input_html: { autocomplete: "first_name" }%>
                      <%= f.input :last_name,
                                  required: true,
                                  input_html: { autocomplete: "last_name" }%>
                      <%= f.input :birth_date, as: :date,
                                  required: true
                                                                           %>
                      <%= f.input :password,
                                  required: true,
                                  hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                                  input_html: { autocomplete: "new-password" } %>
                      <%= f.input :password_confirmation,
                                  required: true,
                                  input_html: { autocomplete: "new-password" } %>
                    </div>
                </div>
                <div class="modal-footer">
                  <div class="form-actions">
                    <%= f.button :submit, "Sign up", class: 'btn btn-primary' %>
                  </div>
                </div>
                  <% end %>
              </div>
            </div>
          </div>
        </ul>
      </div>
    <% end %>
  </nav>